apiVersion: v2
actions:
  - name: "argo-sync"
    events:
      - name: "sh.keptn.event.deployment.triggered"
    tasks:
      - name: "argocd-sync"
        files:
          - /files
        image: "alpine:3.16"
        cmd: ["run.sh"]
